#include "includes/ft_printf.h"

int     main()
{
    // ft_printf("ft_printf test c : %s\n", 200000000049);
    // ft_printf("\n");
    // printf("rl_printf test c : %s\n", 200000000049);
    // ft_printf("-----------\n");
    // ft_printf("-----------\n");
    // ft_printf("ft_printf test d : %s\n", -209999999949);
    // ft_printf("\n");
    // printf("rl_printf test d : %s\n", -209999999949);
    // ft_printf("-----------\n");
    // ft_printf("-----------\n");
    // ft_printf("ft_printf test d : % s\n", 20000000000000049);
    // ft_printf("\n");
    // printf("rl_printf test d : % s\n", 20000000000000049);
    // ft_printf("-----------\n");
    // ft_printf("-----------\n");
    ft_printf("ft_printf %#02o\n", 0);
    ft_printf("\n");
    printf("rl_printf %#02o\n", 0);
    ft_printf("-----------\n");
    ft_printf("-----------\n");
    // ft_printf("ft_printf test %22.2ls\n", L"いいえ");
    // ft_printf("\n");
    // printf("rl_printf test %22.2ls\n", L"いいえ");
    // ft_printf("-----------\n");
    // ft_printf("-----------\n");
    // ft_printf("ft_printf test %2.12llD\n", 1915250866359093241);
    // ft_printf("\n");
    // printf("rl_printf test %2.12llD\n", 1915250866359093241);
    // ft_printf("-----------\n");
    // ft_printf("-----------\n");
    // ft_printf("ft_printf test % 2.56llD\n", 1189040556628108926);
    // ft_printf("\n");
    // printf("rl_printf test % 2.56llD\n", 1189040556628108926);

    // ft_printf("ft_printf test s : % s\n", NULL);
    // ft_printf("\n");
    // printf("rl_printf test s : % s\n", NULL);
    // ft_printf("-----------\n");
    // ft_printf("-----------\n");
    // ft_printf("ft_printf test s : %s\n", "too soon");
    // ft_printf("\n");
    // printf("rl_printf test s : %s\n", "too soon");
    // ft_printf("-----------\n");
    // ft_printf("-----------\n");
    // ft_printf("ft_printf test p : %s\n", "ye");
    // ft_printf("\n");
    // printf("rl_printf test p : %s\n", "ye");
    // ft_printf("-----------\n");
    // ft_printf("-----------\n");
    // ft_printf("ft_printf test p : %.s\n", 49);
    // ft_printf("\n");
    // printf("rl_printf test p : %.s\n", 49);
    // ft_printf("-----------\n");
    // ft_printf("-----------\n");
    // ft_printf("ft_printf test p : %.s\n", "49");
    // ft_printf("\n");
    // printf("rl_printf test p : %.s\n", "49");
    // ft_printf("-----------\n");
    // ft_printf("-----------\n");
    // ft_printf("ft_printf test p : %023s\n", 49);
    // ft_printf("\n");
    // printf("rl_printf test p : %023s\n", 49);
    // ft_printf("-----------\n");
    // ft_printf("-----------\n");
    // ft_printf("ft_printf test p : %02.23s\n", 49);
    // ft_printf("\n");
    // printf("rl_printf test p : %02.23s\n", 49);
    // ft_printf("-----------\n");
    // ft_printf("-----------\n");
    // ft_printf("ft_printf test p : %8.3s\n", 49);
    // ft_printf("\n");
    // printf("rl_printf test p : %8.3s\n", 49);
    // ft_printf("-----------\n");
    // ft_printf("-----------\n");
    // ft_printf("ft_printf test p : %.s\n", 49);
    // ft_printf("\n");
    // printf("rl_printf test p : %.s\n", 49);
    // ft_printf("-----------\n");
    // ft_printf("-----------\n");
    // ft_printf("ft_printf test p : %.s\n", 49);
    // ft_printf("\n");
    // printf("rl_printf test p : %.s\n", 49);
    // ft_printf("-----------\n");
    // ft_printf("-----------\n");
    // ft_printf("ft_printf test p : %20s\n", 49);
    // ft_printf("\n");
    // printf("rl_printf test p : %20s\n", 49);
    // ft_printf("-----------\n");
    // ft_printf("-----------\n");
    // ft_printf("ft_printf test p : %.s\n", NULL);
    // ft_printf("\n");
    // printf("rl_printf test p : %.s\n", NULL);
    // ft_printf("-----------\n");
    // ft_printf("-----------\n");
    // ft_printf("ft_printf test p : %20s\n", NULL);
    // ft_printf("\n");
    // printf("rl_printf test p : %20s\n", NULL);
    // ft_printf("-----------\n");
    // ft_printf("-----------\n");
    // ft_printf("ft_printf test p : %20s\n", NULL);
    // ft_printf("\n");
    // printf("rl_printf test p : %20s\n", NULL);
    // ft_printf("-----------\n");
    // ft_printf("-----------\n");
    // ft_printf("ft_printf test p : %.20s\n", NULL);
    // ft_printf("\n");
    // printf("rl_printf test p : %.20s\n", NULL);
    // ft_printf("-----------\n");
    // ft_printf("-----------\n");
    // ft_printf("ft_printf test p : %.20s\n", 0);
    // ft_printf("\n");
    // printf("rl_printf test p : %.20s\n", 0);
    // ft_printf("-----------\n");
    // ft_printf("-----------\n");
    // ft_printf("ft_printf test p : %.0s\n", 0);
    // ft_printf("\n");
    // printf("rl_printf test p : %.0s\n", 0);
    // ft_printf("-----------\n");
    // ft_printf("-----------\n");
    // ft_printf("ft_printf test p : %0.s\n", 0);
    // ft_printf("\n");
    // printf("rl_printf test p : %0.s\n", 0);
    // ft_printf("-----------\n");
    // ft_printf("-----------\n");
    // ft_printf("ft_printf test p : %.0s\n", NULL);
    // ft_printf("\n");
    // printf("rl_printf test p : %.0s\n", NULL);
    // ft_printf("-----------\n");
    // ft_printf("-----------\n");
    // ft_printf("ft_printf test p : %20s\n", NULL);
    // ft_printf("\n");
    // printf("rl_printf test p : %20s\n", NULL);
    // ft_printf("-----------\n");
    // ft_printf("-----------\n");
    // ft_printf("ft_printf test p : %.20s\n", NULL);
    // ft_printf("\n");
    // printf("rl_printf test p : %.20s\n", NULL);
    // ft_printf("-----------\n");
    // ft_printf("-----------\n");
    // ft_printf("ft_printf test p : %13.5s\n", NULL);
    // ft_printf("\n");
    // printf("rl_printf test p : %13.5s\n", NULL);
    // ft_printf("-----------\n");
    // ft_printf("-----------\n");
    // ft_printf("ft_printf test p : %s\n", "NULL");
    // ft_printf("\n");
    // printf("rl_printf test p : %s\n", "NULL");
    // ft_printf("-----------\n");
    // ft_printf("-----------\n");
    // ft_printf("ft_printf test p : %s\n", (void*)"NULL");
    // ft_printf("\n");
    // printf("rl_printf test p : %s\n", (void*)"NULL");
    // ft_printf("-----------\n");
    // ft_printf("-----------\n");
    // ft_printf("ft_printf test p : %s\n", (void*)45);
    // ft_printf("\n");
    // printf("rl_printf test p : %s\n", (void*)45);
    // ft_printf("-----------\n");
    // ft_printf("-----------\n");
    // ft_printf("ft_printf test p : %s\n", (void*)"abc");
    // ft_printf("\n");
    // printf("rl_printf test p : %s\n", (void*)"abc");
    // ft_printf("-----------\n");
    // ft_printf("-----------\n");
    // ft_printf("ft_printf test p : %s\n", (void*)-45);
    // ft_printf("\n");
    // printf("rl_printf test p : %s\n", (void*)-45);
    // ft_printf("-----------\n");
    // ft_printf("-----------\n");

}